name: Validate

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: macos-26
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install chezmoi
        run: brew install chezmoi
      - name: Lint packages
        run: sh .github/scripts/lint-packages.sh
      - name: Dry run chezmoi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: chezmoi init --promptDefaults --apply -n .
